name: Build

on:
  workflow_call:
    inputs:
      custom-run:
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Custom build (if exist)
        if: "${{ inputs.custom-run != ''}}"
        run: ${{ inputs.custom-run }}

      - name: Build
        if: "${{ inputs.custom-run == ''}}"
        run: pnpm build
