name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
      token:
        required: true

jobs:
  docker-publish-to-registry:
    uses: ./.github/workflows/docker.yml
    with:
      image_name: ${{ inputs.image_name }}
    secrets:
      docker_username: ${{ secrets.docker_username }}
      docker_password: ${{ secrets.docker_password }}

  update-manifest:
    name: Update Kubernetes manifest
    runs-on: ubuntu-latest
    needs: [docker-publish-to-registry]

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
        with:
          repository: KronosMoe/kronos-helm
          ref: "main"
          token: ${{ secrets.token }}

      - name: Git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          echo ${{ github.sha }}
          sed -i "s#appVersion.*#appVersion: ${{ github.sha }}#g" ${{ inputs.image_name }}/Chart.yaml
          git add -A
          git commit -am "update ${{ inputs.image_name }} image to version ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main
